### ISSUE TITLE
worked before, now it doesnt work

### ISSUE THREAD

**Issue by mato200** [cvzi/Spotify-Web-Copy-track-info-to-clipboard-Userscript#2]
latest everything, firefox

**Comment by cvzi** [comment]
It still works for me - at the moment. 
Spotify has probably changed their site. I know that Spotify publishes changes not to all users at the same time. I will probably see the changes in a few hours or few days. Then I can try to fix the script.

**Comment by cvzi** [comment]
As expected, today it doesn't work for me either. I will try to fix it later today 🙂
Edit:
It works again for me 😐

**Comment by cvzi** [comment]
Could you check if it doesn't work anywhere or if it works in some places:
 - one the current playing song in the lower left corner
 - in a playlist
 - in the track list of an album

**Comment by cvzi** [comment]
I found that sometimes the script does not work with Tampermonkey.
The solution is to restart Tampermonkey if that happens:

1. Open Tampermonkey menu
2. Select "Dashboard"
3. Go to "Settings" tab
4. Select "Advanced" under "Config mode" (the first drop down menu)
5. Scroll down to the "Reset" section
6. Press "Restart Tampermonkey"
7. Press F5 on the Spotify tab
8. Script should work again

**Comment by mato200** [comment]
made new clean firefox profile, reinstalled all extensions and scripts, now it works...
